### ISSUE TITLE
The long search for an image from the cache

### ISSUE THREAD

**Issue by MarcSky** [hirokimu/EMTImageCacheManager#1]
I plugged your cache, and faced with the fact that he had long loads images from the cache (5-15 seconds), I think may be in the simulator apple watch no cache? Maybe it's because of that that I upload an image size of 1 MB?

```
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSURL *url = [NSURL URLWithString:_article.image];
        NSData *data = [NSData dataWithContentsOfURL:url];
        NSString *imageName = [[EMTImageCacheManager instance] addOrderedCachedImageWithData:data name:@"image"];
        dispatch_async(dispatch_get_main_queue(), ^{
            NSLog(@"%@", imageName);
            if (imageName) {
                NSLog(@"tut1");
                [row.backImage setImageNamed:imageName];
            }
            else {
                NSLog(@"tut2");
                [row.backImage setImageData:data];
            }
        });
```

The name "image" inside addOrderedCachedImageWithData accident - can because of this?
When I start the application to download one image from the cache comes two keys in the program log. Strange.
Please help, the application for a long time to spin and looks awful.

**Comment by hirokimu** [comment]
Your code will load image from url every time regardless it is in cache or isn't.
Try this.

``` objective-c

// Decide your image name to cache. 
NSString *imageName = [self someMethodThatExtractFileNameFromURL:_article.image];

NSString *cacheName = [[EMTImageCacheManager instance] getOrderedCacheKeyForName:imageName];
if (cacheName) { // This image is in cache. 
    [row.backImage setImageNamed:cacheName];
}
else {
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSURL *url = [NSURL URLWithString:_article.image];
        NSData *data = [NSData dataWithContentsOfURL:url];
        dispatch_async(dispatch_get_main_queue(), ^{
            NSString *cacheName = [[EMTImageCacheManager instance] addOrderedCachedImageWithData:data name:imageName];
            if (cacheName) {
                NSLog(@"tut1");
                [row.backImage setImageNamed:cacheName];
            }
            else {
                NSLog(@"tut2");
                [row.backImage setImageData:data];
            }
       });
   });
}
```

**Comment by MarcSky** [comment]
It seems to work, the question of how he finds the image of the key, such as the format of the name cache is still associated with the time that is necessary and the time to pass. As it is an element?

**Comment by hirokimu** [comment]
You don't need to think about the time. Simply pass the image id which you decided (such as filename or file url) to getOrderedCacheKeyForName / addOrderedCachedImageWithData:name:. Please see "How it works" of readme.

**Comment by MarcSky** [comment]
I just looked at this place ( NSString *key = [NSString stringWithFormat:@"cache%f_%@", [date timeIntervalSince1970], name];) and not a lot of confused, well thank you very much)
